-- Task: Update Employee Department USING STORED PROCEDURE
DELIMITER $$
CREATE procedure UPDATEDEPARTMENT(IN EMPID INT,IN DEPT_NAME VARCHAR(20),OUT MESSAGE VARCHAR(250))
BEGIN
DECLARE PRESENTDEPT VARCHAR(40);
DECLARE CURRENTDEPTID INT;
SELECT DEPARTMENT_NAME INTO PRESENTDEPT FROM DEPARTMENTS WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMP_ID = EMPID);
IF(DEPT_NAME <> PRESENTDEPT) THEN
	SELECT DEPARTMENT_ID INTO CURRENTDEPTID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = DEPT_NAME;
    IF CURRENTDEPTID IS NOT NULL THEN
		UPDATE EMPLOYEES SET DEPARTMENT_ID = CURRENTDEPTID WHERE EMP_ID = EMPID;
		SET MESSAGE = 'SUCCESSFULLY CHANGED THE DEPARTMENT';
	ELSE 
		SET MESSAGE = 'DEPARTMENT NAME DOES NOT MATCHING PLEASE ENTER VALID DEPARTMENT';
	END IF;
ELSE
	SET MESSAGE = 'EMPLOYEE ALDREADY IN THE GIVEN DEPARTMENT';
END IF;
END $$
DELIMITER ;

SET @MSG  = '';
CALL UPDATEDEPARTMENT(101,'HR',@MSG);
SELECT @MSG;






















