use hr;
create table students_details(
roll_no int auto_increment primary key,
name varchar(10),
department varchar(40),
mark int
);

select * from students_details;


select s.*,rank() over(partition by department order by mark desc) STUDENT_RANK from students_details s;

SELECT S.*,
RANK() OVER(PARTITION BY DEPARTMENT ORDER BY MARK DESC) AS STUDENT_RANK,
DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY MARK DESC) AS STUDENT_DENSE_RANK ,
ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY MARK DESC) AS STUDENT_ROW_RANK 
FROM STUDENTS_DETAILS S;

SELECT NAME,LEAD(NAME) OVER(ORDER BY NAME DESC) COMPARE FROM STUDENTS_DETAILS;

SELECT NAME,LAG(NAME) OVER (ORDER BY NAME DESC) COMPARE FROM STUDENTS_DETAILS;

SELECT * FROM STUDENTS_DETAILS;

SHOW TABLES;
SHOW databases;


CREATE TEMPORARY TABLE TEMP(
NAME VARCHAR(32),
CONTACT BIGINT
);

SELECT * FROM TEMP;

insert INTO TEMP VALUES('PRAVEEN',879694);

SELECT * FROM TEMP;


USE HR;

-- MATH FUNCTION
SELECT POWER(2,3),ABS(-3),MOD(16,2),CEIL(30.1),FLOOR(30.1),ROUND(30.5555,2),SQRT(16),SIGN(10),ROUND(RAND()*100),TRUNCATE(30.9023,2) FROM DUAL;

-- DATE FUNCTION
SELECT current_timestamp(),CURRENT_DATE,current_time(),utc_date(),utc_time(),utc_timestamp(),current_user() FROM DUAL;

