USE HR;
DELIMITER $$
CREATE PROCEDURE UPDATESALARY(IN NEW_SALARY INTEGER,IN EMPLOYEE_ID INTEGER,OUT MESSAGE VARCHAR(40))
BEGIN
DECLARE PREV_SALARY INT;
	SELECT SALARY INTO PREV_SALARY FROM EMPLOYEES WHERE EMP_ID = EMPLOYEE_ID;
	IF(NEW_SALARY > PREV_SALARY) THEN
		UPDATE EMPLOYEES SET SALARY = NEW_SALARY WHERE EMP_ID = EMPLOYEE_ID;
        SET MESSAGE = 'SALARY UPDATED SUCCESSFULLY';
	ELSE  
		SET MESSAGE = 'CURRENT SALARY IS HIGHER THAN NEW SALARY';
    END IF;
END $$
DELIMITER ;

DROP procedure UPDATESALARY;

SELECT * FROM EMPLOYEES;

SET @MSG = '';
CALL UPDATESALARY(70000,101,@MSG);
SELECT @MSG;

SELECT * FROM EMPLOYEES;



USE HR;
DELIMITER $$
CREATE PROCEDURE UPDATESALARY(IN NEW_SALARY INTEGER,IN EMPLOYEE_ID INTEGER)
BEGIN
DECLARE PREV_SALARY INT;
DECLARE MESSAGE VARCHAR(50);
	SELECT SALARY INTO PREV_SALARY FROM EMPLOYEES WHERE EMP_ID = EMPLOYEE_ID;
	IF(NEW_SALARY > PREV_SALARY) THEN
		UPDATE EMPLOYEES SET SALARY = NEW_SALARY WHERE EMP_ID = EMPLOYEE_ID;
        SET MESSAGE = 'SALARY UPDATED SUCCESSFULLY';
        select message;
	ELSE  
		SET MESSAGE = 'CURRENT SALARY IS HIGHER THAN NEW SALARY';
        select message ;
    END IF;
END $$
DELIMITER ;


CALL UPDATESALARY(80000,101);

SELECT * FROM EMPLOYEES;





DELIMITER $$
CREATE procedure UPDATEDEPARTMENT(IN EMPID INT,IN DEPT_NAME VARCHAR(20),OUT MESSAGE VARCHAR(250))
BEGIN
DECLARE PRESENTDEPT VARCHAR(40);
DECLARE CURRENTDEPTID INT;
SELECT DEPARTMENT_NAME INTO PRESENTDEPT FROM DEPARTMENTS WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMP_ID = EMPID);
IF(DEPT_NAME <> PRESENTDEPT) THEN
	SELECT DEPARTMENT_ID INTO CURRENTDEPTID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = DEPT_NAME;
    IF CURRENTDEPTID IS NOT NULL THEN
		UPDATE EMPLOYEES SET DEPARTMENT_ID = CURRENTDEPTID WHERE EMP_ID = EMPID;
		SET MESSAGE = 'SUCCESSFULLY CHANGED THE DEPARTMENT';
	ELSE 
		SET MESSAGE = 'DEPARTMENT NAME DOES NOT MATCHING PLEASE ENTER VALID DEPARTMENT';
	END IF;
ELSE
	SET MESSAGE = 'EMPLOYEE ALDREADY IN THE GIVEN DEPARTMENT';
END IF;
END $$
DELIMITER ;

SET @MSG  = '';
CALL UPDATEDEPARTMENT(101,'HR',@MSG);
SELECT @MSG;
